language: java
sudo: false

install: true
script: ./travis.sh

matrix:
  fast_finish: true
  include:
    # verify
    - jdk: oraclejdk8
      TEST=ci

    # package
    - jdk: oraclejdk8
      TEST=package
