language: java
sudo: false

install: true
script: ./travis.sh

cache:
  apt: true
  directories:
    - ~/.m2

addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet

matrix:
  fast_finish: true
  include:
    # verify
    - jdk: oraclejdk8
      env: TEST=ci

    # package
    - jdk: oraclejdk8
      env: TEST=nondex
